name: local_ai_desktop
description: "Desktop Interface AirLLM Work on Macbook Air"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.11.5
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  image_path: "assets/images/logo.png"
  adaptive_icon_foreground: assets/images/logo.png
  adaptive_icon_background: "#0A1A2F"
  macos:
    generate: true
    image_path: "assets/images/logo.png"

flutter:
  uses-material-design: true
